title: "AUTOBOT"

states:
  hello:
    text: "Hello, what is your sex?"
    inline_buttons:
      - row:
        - text: man
          callback_data: man
        - text: woman
          callback_data: woman
      - row:
        - text: don't know :(
          callback_data: dunno
    command: "start"
  man:
    text: "Your choice is: Man"
    add_back_button: yes
  woman:
    text: "Your choice is: Woman"
    add_back_button: yes
  other:
    text: "Other?"
    add_back_button: yes

transitions:
  - from: hello
    to: man
    conditions:
      data:
        - "man"

  - from: hello
    to: woman
    conditions:
      data:
        - "woman"

  - from: hello
    to: other
    conditions:
      data:
        - "dunno"
